image: ubuntu:focal

definitions:
  caches:
    downloads: ~/downloads
  steps:
    - step: &build
        name: Build and Test
        artifacts:
          - build*.tar.gz
        script:
          - apt-get -qq update
          - DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common
          - add-apt-repository -y ppa:ondrej/php
          - apt-get -qq update
          - >-
            DEBIAN_FRONTEND=noninteractive apt-get install -y
            unzip wget curl git
            php8.0-common php8.0-cli php8.0-curl php-json php8.0-mbstring php8.0-readline php8.0-xml php8.0-zip
         #  php8.0-mysql php8.0-soap php8.0-gd php8.0-opcache php-apcu php8.0-yaml php8.0-http php8.0-bcmath php8.0-bz2
          - curl -sS https://getcomposer.org/installer -o composer-setup.php
          - php composer-setup.php --install-dir=. --filename=composer
          - ./composer -V
          - ./composer install --no-plugins --no-scripts --no-progress --optimize-autoloader --no-interaction --ignore-platform-reqs

          # Prepare .env for environment
          - cp ".env.$BITBUCKET_DEPLOYMENT_ENVIRONMENT" .env
          #- echo "DB_PASSWORD=$DB_PASSWORD">>.env
          - rm .env.*

          # Execute tests
          #- php vendor/bin/phpunit tests/.

          # Create a build
          - export VERSION=${BITBUCKET_REPO_SLUG}-${BITBUCKET_BRANCH}${BITBUCKET_TAG}-${BITBUCKET_BUILD_NUMBER}
          - export BUILD=build-${VERSION}.tar.gz
          - date>build.txt
          - echo $VERSION>>build.txt
          - git log -1>>build.txt
          # Create the artifacts file first, otherwise you will get an error "file changed as we read it"
          - touch $BUILD
          - >-
            tar --exclude=$BUILD
            --exclude=./tests/Concerns
            --exclude=./tests/Feature
            --exclude=./tests/Unit
            --exclude=./tests/CreatesApplication.php
            --exclude=./tests/TestCase.php
            --exclude=./logs/*
            --exclude=.git
            --exclude=phpunit.xml
            --exclude=composer.lock
            --exclude=bitbucket-pipelines.yml
            --exclude=phpunit.xml
            --exclude=server.php
            --exclude=webpack.mix.js
            --exclude=.php_*
            --exclude=.styleci.yml
            --exclude=_ide_helper_models.php
            -zcvf $BUILD .
          - ls -lah
          - md5sum $BUILD
    - step: &deploy-to-staging
        name: Deploy to staging
        image: alpine:3.10
        script:
          - export VERSION=${BITBUCKET_REPO_SLUG}-${BITBUCKET_BRANCH}${BITBUCKET_TAG}-${BITBUCKET_BUILD_NUMBER}
          - export BUILD=build-${VERSION}.tar.gz
          - apk --no-cache add openssh-client
          - scp -P 24480 $BUILD www-data@dev.freeping.io:/tmp/
          - cat local_deployment.sh|ssh -p 24480 www-data@dev.freeping.io "BUILD=$BUILD bash -e"

    - step: &deploy-to-prod
        name: Deploy to prod
        image: alpine:3.10
        script:
          - export VERSION=${BITBUCKET_REPO_SLUG}-${BITBUCKET_BRANCH}${BITBUCKET_TAG}-${BITBUCKET_BUILD_NUMBER}
          - export BUILD=build-${VERSION}.tar.gz
          - apk --no-cache add openssh-client
          - scp -P 24480 $BUILD www-data@app1.freeping.io:/tmp/
          - cat local_deployment.sh|ssh -p 24480 www-data@app1.freeping.io "BUILD=$BUILD bash -e"

pipelines:
  branches:
    develop:
      - step:
          deployment: Staging
          <<: *build
      - step: *deploy-to-staging
  tags:
    release-*:
      - step:
          deployment: Production
          <<: *build
      - step: *deploy-to-prod
    hotfix-*:
      - step:
          deployment: Production
          <<: *build
      - step: *deploy-to-prod
  # Use
  # git tag release-$(date +%s) -m "release $(date +%c)" && git push --follow-tags
  # to trigger a release to prod
